#string and string function
a = "UNKNOWN Hacking by Pugalmani"
print("value : ", a)
print(type(a))
print("\n-----Mostly-Using-Function-----\n")
print("--(function)--\t\t--(Example)--\n")
print("lower()  \t\t", a.lower())
print("upper()  \t\t", a.upper())
print("capitalize()  \t\t", a.capitalize())
print("title()  \t\t", a.title())
print("find()  \t\t", a.find("N"))
print("find()  \t\t", a.find("N", 2))
print("count()  \t\t", a.count("N"))
print("endswith()  \t\t", a.endswith("ni"))
print("replace()  \t\t", a.replace("a", "@"))
print("\n-----End-----\n")
a = "UNKNOWN123"
print("value : ", a)
print(type(a))
print("\n-----Mostly-Using-Function-----\n")
print("--(function)--\t\t--(Example)--\n")
print("isupper()  \t\t", a.isupper())
print("islower()  \t\t", a.islower())
print("isalnum()  \t\t", a.isalnum())
print("isalpha()  \t\t", a.isalpha())
print("\n-----End-----\n")
a = "string\nand\nstring\nfunction"
print("value : \n", a)
print(type(a))
print("\n-----Mostly-Using-Function-----\n")
print("--(function)--\t\t--(Example)--\n")
print("splitlines()  \t\t", a.splitlines())
print("splitlines()  \t\t", a.splitlines(True))
print("\n-----End-----\n")
a = "UNKNOWN Hacking by Pugalmani"
print("value : ", a)
print(type(a))
print("\n-----Mostly-Using-Function-----\n")
print("--(function)--\t\t--(Example)--\n")
print("split() \t\t", a.split(" "))
a = "UNKNOWN,Hacking,by,Pugalmani"
print("--(function)--\t\t--(Example)--\n")
print("value : ", a)
print("split()  \t\t", a.split(","))
print("\n-----End-----\n")
a = "   UNKNOWN     "
print("value : ", a)
print("len() : ", len(a))
print("\n-----Mostly-Using-Function-----\n")
print("--(function)--\t\t--(Example)--\n")
print("strip()  \t\t", len(a.strip()))
print("lstrip()  \t\t", len(a.lstrip()))
print("rstrip()  \t\t", len(a.rstrip()))
a = "16-11-2023"
print("value : ", a)
print("\n-----Mostly-Using-Function-----\n")
print("--(function)--\t\t--(Example)--\n")
print("partition()  \t\t", a.partition("-"))
print("\n-----End-----\n")

